# Generated by Django 4.0.5 on 2022-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('empresa', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
