# Generated by Django 4.0.5 on 2022-06-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='id_empresa_colab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='id_empresa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
