# Generated by Django 4.0.5 on 2022-06-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_colaborador_id_empresa_colab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='id_empresa',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
